on:
  push:
    branches:
      - main

jobs:
  test: 
    name: Run Unit Test
    runs-on: ubuntu-22.04
    steps: 
      - name: Run Unit Test 
        run: |
          echo "misal ini akan menjalankan unit test"
      - name: List Files
        run: |
          ls -la
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: List Files After Cloning
        run: |
          ls -la

  build: 
    name: Build Application
    runs-on: ubuntu-22.04
    needs: 
      - test
    steps: 
      - name: Build Application 
        run: |
          echo "misal ini akan build/package aplikasi"

  deploy: 
    name: Deploy Application
    runs-on: ubuntu-22.04
    needs: 
      - build
    steps: 
      - name: Deploy Application
        run: |
          echo "misal ini akan deploy aplikasi ke server"
      - name: Access Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            pwd
            ls -la
            rm -rf study-github
            git clone git@github.com:FriskiIqwan/study-github.git
            ls -la 
            sudo cp -r study-github/* /var/www/html
