on:
  push:
    branches:
      - main

jobs:
  test: 
    name: Run Unit Test
    runs-on: ubuntu-22.04
    needs: 
      - test
    steps: 
      - name: Run Unit Test 
        run: |
          echo "misal ini akan menjalankan unit test"

  build: 
    name: Build Application
    runs-on: ubuntu-22.04
    needs: 
      - build
    steps: 
      - name: Build Application 
        run: |
          echo "misal ini akan build/package aplikasi"

  deploy: 
    name: Deploy Application
    runs-on: ubuntu-22.04
    steps: 
      - name: Deploy Application
        run: |
          echo "misal ini akan deploy aplikasi ke server"
